on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install linters
        run: sudo apt install -y shellcheck

      - name: Run linters
        run: ./run linters

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install testers
        run: sudo apt install -y bats python tmux

      - name: Setup tmux
        run: |
          tmux kill-server 2>/dev/null || true
          tmux start-server
          tmux new-session -t "START-$$" -d

      - name: Run tests
        run: ./run tests --check-stale-snapshots
